version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ordercontrol
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
