server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}
    user: ${DB_USERNAME}
    password: ${DB_USERNAME}
  kafka:
    topics:
      stock-control: stock-control-order-v1
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    listener:
      ack-mode: manual

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

debug: true




